# Generated by Django 4.0.4 on 2022-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_rename_dishes_dish_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcd_id', models.IntegerField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
